/* This file was generated by SableCC (http://www.sablecc.org/). */

package tp6.parser;

import tp6.node.*;
import tp6.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTLPar(@SuppressWarnings("unused") TLPar node)
    {
        this.index = 0;
    }

    @Override
    public void caseTRPar(@SuppressWarnings("unused") TRPar node)
    {
        this.index = 1;
    }

    @Override
    public void caseTPlus(@SuppressWarnings("unused") TPlus node)
    {
        this.index = 2;
    }

    @Override
    public void caseTMinus(@SuppressWarnings("unused") TMinus node)
    {
        this.index = 3;
    }

    @Override
    public void caseTMultiplier(@SuppressWarnings("unused") TMultiplier node)
    {
        this.index = 4;
    }

    @Override
    public void caseTDiv(@SuppressWarnings("unused") TDiv node)
    {
        this.index = 5;
    }

    @Override
    public void caseTModulo(@SuppressWarnings("unused") TModulo node)
    {
        this.index = 6;
    }

    @Override
    public void caseTSup(@SuppressWarnings("unused") TSup node)
    {
        this.index = 7;
    }

    @Override
    public void caseTInf(@SuppressWarnings("unused") TInf node)
    {
        this.index = 8;
    }

    @Override
    public void caseTEqual(@SuppressWarnings("unused") TEqual node)
    {
        this.index = 9;
    }

    @Override
    public void caseTSemi(@SuppressWarnings("unused") TSemi node)
    {
        this.index = 10;
    }

    @Override
    public void caseTIf(@SuppressWarnings("unused") TIf node)
    {
        this.index = 11;
    }

    @Override
    public void caseTThen(@SuppressWarnings("unused") TThen node)
    {
        this.index = 12;
    }

    @Override
    public void caseTElse(@SuppressWarnings("unused") TElse node)
    {
        this.index = 13;
    }

    @Override
    public void caseTWhile(@SuppressWarnings("unused") TWhile node)
    {
        this.index = 14;
    }

    @Override
    public void caseTRead(@SuppressWarnings("unused") TRead node)
    {
        this.index = 15;
    }

    @Override
    public void caseTPrint(@SuppressWarnings("unused") TPrint node)
    {
        this.index = 16;
    }

    @Override
    public void caseTNumber(@SuppressWarnings("unused") TNumber node)
    {
        this.index = 17;
    }

    @Override
    public void caseTNewLine(@SuppressWarnings("unused") TNewLine node)
    {
        this.index = 18;
    }

    @Override
    public void caseTObrace(@SuppressWarnings("unused") TObrace node)
    {
        this.index = 19;
    }

    @Override
    public void caseTCbrace(@SuppressWarnings("unused") TCbrace node)
    {
        this.index = 20;
    }

    @Override
    public void caseTAssign(@SuppressWarnings("unused") TAssign node)
    {
        this.index = 21;
    }

    @Override
    public void caseTComa(@SuppressWarnings("unused") TComa node)
    {
        this.index = 22;
    }

    @Override
    public void caseTIdentifier(@SuppressWarnings("unused") TIdentifier node)
    {
        this.index = 23;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 24;
    }
}
