/* This file was generated by SableCC (http://www.sablecc.org/). */

package tp6.node;

import java.util.*;
import tp6.analysis.*;

@SuppressWarnings("nls")
public final class ABlock extends PBlock
{
    private TObrace _obrace_;
    private final LinkedList<PStatement> _statement_ = new LinkedList<PStatement>();
    private TCbrace _cbrace_;

    public ABlock()
    {
        // Constructor
    }

    public ABlock(
        @SuppressWarnings("hiding") TObrace _obrace_,
        @SuppressWarnings("hiding") List<PStatement> _statement_,
        @SuppressWarnings("hiding") TCbrace _cbrace_)
    {
        // Constructor
        setObrace(_obrace_);

        setStatement(_statement_);

        setCbrace(_cbrace_);

    }

    @Override
    public Object clone()
    {
        return new ABlock(
            cloneNode(this._obrace_),
            cloneList(this._statement_),
            cloneNode(this._cbrace_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABlock(this);
    }

    public TObrace getObrace()
    {
        return this._obrace_;
    }

    public void setObrace(TObrace node)
    {
        if(this._obrace_ != null)
        {
            this._obrace_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._obrace_ = node;
    }

    public LinkedList<PStatement> getStatement()
    {
        return this._statement_;
    }

    public void setStatement(List<PStatement> list)
    {
        this._statement_.clear();
        this._statement_.addAll(list);
        for(PStatement e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    public TCbrace getCbrace()
    {
        return this._cbrace_;
    }

    public void setCbrace(TCbrace node)
    {
        if(this._cbrace_ != null)
        {
            this._cbrace_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cbrace_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._obrace_)
            + toString(this._statement_)
            + toString(this._cbrace_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._obrace_ == child)
        {
            this._obrace_ = null;
            return;
        }

        if(this._statement_.remove(child))
        {
            return;
        }

        if(this._cbrace_ == child)
        {
            this._cbrace_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._obrace_ == oldChild)
        {
            setObrace((TObrace) newChild);
            return;
        }

        for(ListIterator<PStatement> i = this._statement_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PStatement) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._cbrace_ == oldChild)
        {
            setCbrace((TCbrace) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
