/* This file was generated by SableCC (http://www.sablecc.org/). */

package tp6.node;

import tp6.analysis.*;

@SuppressWarnings("nls")
public final class AIntegervalueUniexpression extends PUniexpression
{
    private PIntegervalue _integervalue_;

    public AIntegervalueUniexpression()
    {
        // Constructor
    }

    public AIntegervalueUniexpression(
        @SuppressWarnings("hiding") PIntegervalue _integervalue_)
    {
        // Constructor
        setIntegervalue(_integervalue_);

    }

    @Override
    public Object clone()
    {
        return new AIntegervalueUniexpression(
            cloneNode(this._integervalue_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIntegervalueUniexpression(this);
    }

    public PIntegervalue getIntegervalue()
    {
        return this._integervalue_;
    }

    public void setIntegervalue(PIntegervalue node)
    {
        if(this._integervalue_ != null)
        {
            this._integervalue_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._integervalue_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._integervalue_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._integervalue_ == child)
        {
            this._integervalue_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._integervalue_ == oldChild)
        {
            setIntegervalue((PIntegervalue) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
