/* This file was generated by SableCC (http://www.sablecc.org/). */

package tp6.node;

import tp6.analysis.*;

@SuppressWarnings("nls")
public final class AModuloOperatorarith extends POperatorarith
{
    private TModulo _modulo_;

    public AModuloOperatorarith()
    {
        // Constructor
    }

    public AModuloOperatorarith(
        @SuppressWarnings("hiding") TModulo _modulo_)
    {
        // Constructor
        setModulo(_modulo_);

    }

    @Override
    public Object clone()
    {
        return new AModuloOperatorarith(
            cloneNode(this._modulo_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAModuloOperatorarith(this);
    }

    public TModulo getModulo()
    {
        return this._modulo_;
    }

    public void setModulo(TModulo node)
    {
        if(this._modulo_ != null)
        {
            this._modulo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._modulo_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._modulo_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._modulo_ == child)
        {
            this._modulo_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._modulo_ == oldChild)
        {
            setModulo((TModulo) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
