/* This file was generated by SableCC (http://www.sablecc.org/). */

package tp6.node;

import tp6.analysis.*;

@SuppressWarnings("nls")
public final class AMultiplierOperatorarith extends POperatorarith
{
    private TMultiplier _multiplier_;

    public AMultiplierOperatorarith()
    {
        // Constructor
    }

    public AMultiplierOperatorarith(
        @SuppressWarnings("hiding") TMultiplier _multiplier_)
    {
        // Constructor
        setMultiplier(_multiplier_);

    }

    @Override
    public Object clone()
    {
        return new AMultiplierOperatorarith(
            cloneNode(this._multiplier_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultiplierOperatorarith(this);
    }

    public TMultiplier getMultiplier()
    {
        return this._multiplier_;
    }

    public void setMultiplier(TMultiplier node)
    {
        if(this._multiplier_ != null)
        {
            this._multiplier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._multiplier_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._multiplier_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._multiplier_ == child)
        {
            this._multiplier_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._multiplier_ == oldChild)
        {
            setMultiplier((TMultiplier) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
