/* This file was generated by SableCC (http://www.sablecc.org/). */

package tp6.node;

import tp6.analysis.*;

@SuppressWarnings("nls")
public final class AOperatorarithOperator extends POperator
{
    private POperatorarith _operatorarith_;

    public AOperatorarithOperator()
    {
        // Constructor
    }

    public AOperatorarithOperator(
        @SuppressWarnings("hiding") POperatorarith _operatorarith_)
    {
        // Constructor
        setOperatorarith(_operatorarith_);

    }

    @Override
    public Object clone()
    {
        return new AOperatorarithOperator(
            cloneNode(this._operatorarith_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOperatorarithOperator(this);
    }

    public POperatorarith getOperatorarith()
    {
        return this._operatorarith_;
    }

    public void setOperatorarith(POperatorarith node)
    {
        if(this._operatorarith_ != null)
        {
            this._operatorarith_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._operatorarith_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._operatorarith_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._operatorarith_ == child)
        {
            this._operatorarith_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._operatorarith_ == oldChild)
        {
            setOperatorarith((POperatorarith) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
