/* This file was generated by SableCC (http://www.sablecc.org/). */

package tp6.node;

import tp6.analysis.*;

@SuppressWarnings("nls")
public final class APrintSStatement extends PStatement
{
    private PPrintS _printS_;

    public APrintSStatement()
    {
        // Constructor
    }

    public APrintSStatement(
        @SuppressWarnings("hiding") PPrintS _printS_)
    {
        // Constructor
        setPrintS(_printS_);

    }

    @Override
    public Object clone()
    {
        return new APrintSStatement(
            cloneNode(this._printS_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPrintSStatement(this);
    }

    public PPrintS getPrintS()
    {
        return this._printS_;
    }

    public void setPrintS(PPrintS node)
    {
        if(this._printS_ != null)
        {
            this._printS_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._printS_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._printS_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._printS_ == child)
        {
            this._printS_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._printS_ == oldChild)
        {
            setPrintS((PPrintS) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
