/* This file was generated by SableCC (http://www.sablecc.org/). */

package tp6.node;

import tp6.analysis.*;

@SuppressWarnings("nls")
public final class ASupOperatorlogique extends POperatorlogique
{
    private TSup _sup_;

    public ASupOperatorlogique()
    {
        // Constructor
    }

    public ASupOperatorlogique(
        @SuppressWarnings("hiding") TSup _sup_)
    {
        // Constructor
        setSup(_sup_);

    }

    @Override
    public Object clone()
    {
        return new ASupOperatorlogique(
            cloneNode(this._sup_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASupOperatorlogique(this);
    }

    public TSup getSup()
    {
        return this._sup_;
    }

    public void setSup(TSup node)
    {
        if(this._sup_ != null)
        {
            this._sup_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._sup_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._sup_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._sup_ == child)
        {
            this._sup_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._sup_ == oldChild)
        {
            setSup((TSup) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
