/* This file was generated by SableCC (http://www.sablecc.org/). */

package tp6.node;

import tp6.analysis.*;

@SuppressWarnings("nls")
public final class AUniexpressionExpression extends PExpression
{
    private PUniexpression _uniexpression_;

    public AUniexpressionExpression()
    {
        // Constructor
    }

    public AUniexpressionExpression(
        @SuppressWarnings("hiding") PUniexpression _uniexpression_)
    {
        // Constructor
        setUniexpression(_uniexpression_);

    }

    @Override
    public Object clone()
    {
        return new AUniexpressionExpression(
            cloneNode(this._uniexpression_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAUniexpressionExpression(this);
    }

    public PUniexpression getUniexpression()
    {
        return this._uniexpression_;
    }

    public void setUniexpression(PUniexpression node)
    {
        if(this._uniexpression_ != null)
        {
            this._uniexpression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._uniexpression_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._uniexpression_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._uniexpression_ == child)
        {
            this._uniexpression_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._uniexpression_ == oldChild)
        {
            setUniexpression((PUniexpression) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
