version: "3"
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "8080:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock

  nginx_1:
        image: nginx:latest
        restart: always
        environment: 
          VIRTUAL_HOST: m
  nginx_2:
        image: nginx:latest
        restart: always
        environment: 
          VIRTUAL_HOST: m   
 